### ISSUE TITLE
Problem with some images (not all) while running pretrained open images model

### ISSUE THREAD

**Issue by PurveshChhajed** [Alibaba-MIIL/ASL#32]
RuntimeError: Given groups=1, weight of size [76, 48, 3, 3], expected input[1, 64, 112, 112] to have 48 channels, but got 64 channels instead

Actually it is giving error on small PNG files, on the other hand if we convert the same file to JPG (with same size) it is working

Can u explain why it is so?

Thanks.

**Comment by mrT23** [comment]
give significantly more details. 
provide a reproduction code

**Comment by PurveshChhajed** [comment]
> give significantly more details.
> provide a reproduction code

Traceback (most recent call last):
  File "/home/user1/anaconda3/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user1/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/user1/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/user1/anaconda3/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/user1/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/user1/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 32, in image_tag
    tags = model(serv_path)
  File "/home/user1/Image_tagging/content/ASL-main/model.py", line 53, in model
    output = torch.squeeze(torch.sigmoid(model(tensor_batch)))
  File "/home/user1/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user1/Image_tagging/content/ASL-main/src/models/tresnet/tresnet.py", line 209, in forward
    x = self.body(x)
  File "/home/user1/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user1/.local/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/home/user1/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user1/.local/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/home/user1/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user1/.local/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 423, in forward
    return self._conv_forward(input, self.weight)
  File "/home/user1/.local/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 420, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Given groups=1, weight of size [76, 48, 3, 3], expected input[1, 64, 112, 112] to have 48 channels, but got 64 channels instead

**Comment by mrT23** [comment]
i recommend reviewing online how to properly open issues in GitHub. 

this is not a proper code (python code, not the error message ).
the code you provide should run also on my computer.

I will ignore future issues that don't follow basic rules for reproducibility and understandability

**Comment by PurveshChhajed** [comment]
sorry for the inconvenience,
 but want to mention that on converting the (the problematic png, mainly small size png files) png image to jpg, error got solved.
But thanks. And it is great piece of art.
